# Change these first
owner: hst1189 # GitHub username
repo: upptime  # GitHub repository name

sites:
  - name: grapehut.us.kg
    url: https://www.grapehut.us.kg

status-website:
  # Add your custom domain name, or baseUrl
  # cname: grapehut.us.kg
  baseUrl: /upptime
  
  name: Upptime    # Status website title
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg  # Status website logo
  introTitle: 
  introMessage:
  theme: light
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
