# Change these first
owner: hst1189 # GitHub username
repo: upptime  # GitHub repository name

sites:
  - name: grapehut.us.kg
    url: https://www.grapehut.us.kg

status-website:    # Status website (optional)
  name: Upptime    # Status website title
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg  # Status website logo
  theme: light
  
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: grapehut.us.kg
  # baseUrl: /your-repo-name

  introTitle: 
  introMessage:
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
